import E1_a).py 	
import E1_b).py 	
import E1_c).py 	
import E1_d).py 	
import E2_a).py 	
import E2_b).py 	
import E2_c).py 	
import E2_d).py 	
import E3_a).py 	
import E3_b).py 	
import E3_c).py 	
import E4.py 	
import E5_a).py 	
import E5_b).py 	
import E5_c).py 	
import E6.py 
import E7.py 	
import grafica1a.png 	
import grafica1b.png 	
import grafica1c.png 	
import grafica1d.png 	
import grafica2a.png 	
import grafica2b.png 
import grafica2c.png 
import grafica2d.png 	
import grafica3a.png 	
import grafica3b.png 	
import grafica3c.png	
import grafica4.png	
import grafica5a.png 	
import grafica5b.png 	
import grafica5c.png	
import grafica6.png
import grafica7.png
